# Topic Modeling on Pitchfork Descriptors

In [17]:
from ArtistReviewAnalyzer import ArtistReviewAnalyzer

from pprint import pprint
import numpy as np
import json
import datetime
import pandas as pd
import pickle
import gensim.corpora as corpora

In [2]:
pf = ArtistReviewAnalyzer()

In [3]:
t0 = datetime.datetime.now()  # ============================================================
pf.build(file_loc="../pitchfork_descriptors.json", min_df=2, max_df=0.8)
t1 = datetime.datetime.now()  # ============================================================
print((t1 - t0).total_seconds())   # =======================================================

184.996229


In [4]:
t0 = datetime.datetime.now()  # ============================================================
pf.run_and_set_lda_model(num_topics=14)
t1 = datetime.datetime.now()  # ============================================================
print((t1 - t0).total_seconds())   # =======================================================

54.817466


In [5]:
pd.DataFrame(pf.print_lda_topics())

0       1        2           3       4          5            6  \
0         late     new    first    producer    feel       year  songwriting   
1          pop     new    debut         rap    solo       rock        offer   
2          new     pop     band       debut  record         lp         punk   
3          pop   debut   second         new  singer       band         self   
4          new   debut   rapper        band  singer     second         year   
5        debut  record      pop     attempt  singer     decade         full   
6       singer  rapper     year        late    soul      voice        first   
7       record    band     live         hop  singer     former        group   
8   songwriter     new   singer         pop    work       star         good   
9       record    look    today        take    past  pitchfork  significant   
10         new    late  release     feature    good       make       rapper   
11        year  rapper     late        work  record      first         rock   
12         pop  singer   record  songwriter  second       late          new   
13       guest    solo   singer       debut  rapper    atlanta         late   

               7        8           9  
0   experimental      pop        None  
1           band     year      rapper  
2       producer     make       first  
3          first   record        year  
4       producer    first         pop  
5            new     late    producer  
6       producer       lp         new  
7            hip     year      return  
8           full    debut        late  
9          depth  archive    eligible  
10           pop    debut        None  
11          band      new     project  
12         style  deliver     release  
13          rock      new  songwriter

In [6]:
t0 = datetime.datetime.now()  # ============================================================
pflda_5 = pf.run_lda_model(num_topics=5)
t1 = datetime.datetime.now()  # ============================================================
print((t1 - t0).total_seconds())   # =======================================================

52.837455


In [7]:
pf.set_lda_model(pflda_5)
pd.DataFrame(pf.print_lda_topics())

0       1      2       3          4       5     6            7  \
0     new    late   star   first       band  record  year       decade   
1  record   today   past    look  pitchfork   depth  take  significant   
2     pop   debut    new    year     record    late   rap        guest   
3     pop  singer  debut  second        new  record  late         band   
4  rapper    year  debut  singer   producer    band   new        first   

         8       9  
0  feature    None  
1  archive  sunday  
2     band   first  
3     year  rapper  
4      pop  record

## new

In [8]:
pf2 = ArtistReviewAnalyzer()

In [10]:
t0 = datetime.datetime.now()  # ============================================================
pf2.build(file_loc="../pitchfork_descriptors.json", min_df=10, max_df=0.65)
pf2.run_and_set_lda_model(num_topics=10)
t1 = datetime.datetime.now()  # ============================================================
print((t1 - t0).total_seconds())   # =======================================================

236.681582


In [11]:
pd.DataFrame(pf2.print_lda_topics())

0       1       2       3           4            5        6  \
0     new    late   first    star     feature  songwriting     year   
1     new     pop  rapper    year        self     producer    debut   
2    band     new    make  record         pop          rap     rock   
3     pop   debut     new  second      singer         band     year   
4   first     new  rapper   debut        year       singer     band   
5   debut    late  rapper     pop     release       record     full   
6     new  rapper    late  singer      record         year  feature   
7  record     pop    rock    band         new        first   return   
8     pop    make    rock  singer  songwriter          rap    debut   
9  record    look   today    past        take    pitchfork    depth   

             7         8         9  
0       decade      None      None  
1       second      folk      None  
2         dark   tribute     guest  
3         late     first  producer  
4      project      late      None  
5         work      turn      None  
6         work  producer   release  
7         find       hop  producer  
8         late    second      take  
9  significant   archive  eligible

In [12]:
#### NEW #####
pf3 = ArtistReviewAnalyzer()
t0 = datetime.datetime.now()  # ============================================================
pf3.build(file_loc="../pitchfork_descriptors.json", min_df=2, max_df=0.5)
pf3.run_and_set_lda_model(num_topics=10)
t1 = datetime.datetime.now()  # ============================================================
print((t1 - t0).total_seconds())   # =======================================================

219.933785


In [13]:
pd.DataFrame(pf3.print_lda_topics())

0       1       2       3           4            5        6  \
0     new    late   first    star     feature  songwriting     year   
1     new     pop  rapper    year        self     producer    debut   
2    band     new    make  record         pop          rap     rock   
3     pop   debut     new  second      singer         band     year   
4   first     new  rapper   debut        year       singer     band   
5   debut    late  rapper     pop     release       record     full   
6     new  rapper    late  singer      record         year  feature   
7  record     pop    rock    band         new        first   return   
8     pop    make    rock  singer  songwriter          rap    debut   
9  record    look   today    past        take    pitchfork    depth   

             7         8         9  
0       decade      None      None  
1       second      folk      None  
2         dark   tribute     guest  
3         late     first  producer  
4      project      late      None  
5         work      turn      None  
6         work  producer   release  
7         find       hop  producer  
8         late    second      take  
9  significant   archive  eligible

## Export topic model

In [14]:
pf3.lda_model.print_topics()

[(0,
  '0.010*"new" + 0.007*"late" + 0.006*"first" + 0.006*"star" + 0.005*"feature" + 0.005*"-" + 0.004*"songwriting" + 0.004*"year" + 0.004*"r&b" + 0.004*"decade"'),
 (1,
  '0.015*"new" + 0.015*"pop" + 0.005*"rapper" + 0.005*"-" + 0.005*"year" + 0.005*"self" + 0.005*"producer" + 0.004*"debut" + 0.004*"second" + 0.004*"folk"'),
 (2,
  '0.007*"band" + 0.006*"new" + 0.006*"make" + 0.005*"record" + 0.005*"pop" + 0.005*"rap" + 0.005*"rock" + 0.004*"dark" + 0.004*"tribute" + 0.004*"guest"'),
 (3,
  '0.018*"pop" + 0.011*"debut" + 0.008*"new" + 0.008*"second" + 0.007*"singer" + 0.007*"band" + 0.006*"year" + 0.005*"late" + 0.005*"first" + 0.005*"producer"'),
 (4,
  '0.008*"first" + 0.007*"new" + 0.007*"rapper" + 0.007*"debut" + 0.007*"year" + 0.007*"singer" + 0.006*"band" + 0.005*"-" + 0.004*"project" + 0.004*"late"'),
 (5,
  '0.009*"debut" + 0.009*"late" + 0.008*"rapper" + 0.007*"pop" + 0.007*"release" + 0.006*"." + 0.006*"record" + 0.006*"full" + 0.004*"work" + 0.004*"turn"'),
 (6,
  '0.010*

In [35]:
id2word = corpora.Dictionary(pf3.tokenized_reviews)
d2b = id2word.doc2bow

In [36]:
test_bow = d2b(pf3.narrow_to_vocabulary(pf3.super_tokenize("rock pop song pop")))

In [37]:
id2word[283]

'rock'

In [38]:
pf3.lda_model.get_document_topics(test_bow)

[(3, 0.9074459),
 (4, 0.011216138),
 (6, 0.011178305),
 (8, 0.010206816),
 (9, 0.012642945)]

In [39]:
artist2id = {i: a for i, a in enumerate(pf3.artists_list)}

In [44]:
len(pf3.tokenized_reviews)

1201

In [43]:
artist2topics = {}
threshold_prob = 0.7
for i,artist_review in enumerate(pf3.tokenized_reviews):
    review_bow = d2b(artist_review)
    print(artist_review)
    print(review_bow)
    print()
    print()
    likely_topics = pf3.lda_model.get_document_topics(review_bow)
    topic_ids = [topic_id for topic_id,topic_prob in likely_topics if topic_prob > threshold_prob]
    artist2topics[pf3.artists_list[i]] = topic_ids

['late', 'signee', 'uicideboy$', 'label', 'atlanta', 'skater', 'turn', 'rapper', 'voice', 'aggressive', 'gleeful', 'new', 'tape', 'serious', 'rapping']
[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1)]


['late', 'incarcerate', 'l.a', '.', 'rapper', 'stem', 'frenzied', 'recording', 'period', 'go', 'prison', 'hour', 'live', 'reliable', 'street', 'rap', 'continue', 'shape', 'contour', 'psyche', 'rapper', 'final', 'day', 'freedom']
[(4, 1), (6, 2), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1)]


['mark', 'year', 'set', 'path', 'dour', 'slow', 'motion', 'techno', 'manchester', 'musician', 'return', 'familiar', 'palette', 'ashen', 'mood', 'richly', 'textured', 'electronic']
[(36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1), (45, 1), (46, 1), (47

['cluster', 'ensemble', 'tackle', 'philip', 'iconic', 'early', 'work', 'crisply', 'clearly', 'perhaps', 'history']
[(207, 1), (366, 1), (382, 1), (779, 1), (871, 1), (1206, 1), (2953, 1), (3139, 1), (3140, 1), (3141, 1), (3142, 1)]


['life', 'gospel', 'singer', 'washington', 'phillip', 'shroud', 'mystery', 'year', 'gentle', 'measured', 'unearthly', 'play', 'handmade', 'instrument', 'still', 'world']
[(53, 1), (78, 1), (220, 1), (360, 1), (462, 1), (695, 1), (897, 1), (1214, 1), (3143, 1), (3144, 1), (3145, 1), (3146, 1), (3147, 1), (3148, 1), (3149, 1), (3150, 1)]


['phishs', 'instinctive', 'new', 'studio', 'pleasant', 'surprise', 'small', 'joy', 'unlikely', 'course', 'correction']
[(5, 1), (134, 1), (377, 1), (657, 1), (1674, 1), (1680, 1), (2047, 1), (2903, 1), (2904, 1), (2905, 1), (2906, 1)]


['sir', 'paul', 'present', 'resequence', 'alternate', 'universe', 'version', 'last', 'year', 'trilogy', 'complete', 'release', 'perform', 'beck', 'phoebe', 'bridger', 'st', '.', 'vincent', 

['uk', 'singer', 'refine', 'moody', 'aquatic', 'narrowly', 'escape', 'adult', 'contemporary', 'fate', 'narcotic', 'electronic', 'pop', 'asmr', 'undertone']
[(38, 1), (78, 1), (87, 1), (95, 1), (221, 1), (480, 1), (815, 1), (925, 1), (3077, 1), (3452, 1), (4534, 1), (4535, 1), (4536, 1), (4537, 1), (4538, 1)]


['josh', 'tillman', 'still', 'self', 'absorbed', 'fourth', 'full', 'length', 'father', 'john', 'misty', 'exhibit', 'new', 'sense', 'empathy', 'vulnerability', 'losing', 'none', 'wit']
[(5, 1), (76, 1), (360, 1), (574, 1), (575, 1), (738, 1), (1411, 1), (1710, 1), (3091, 1), (3232, 1), (3291, 1), (4539, 1), (4540, 1), (4541, 1), (4542, 1), (4543, 1), (4544, 1), (4545, 1), (4546, 1)]


['year', 'old', 'singer', 'songwriter', 'third', 'serene', 'folk', 'pop', 'mellow', 'soul', 'tinge', 'melancholy', 'clarity', 'age']
[(53, 1), (78, 1), (95, 1), (155, 1), (334, 1), (412, 1), (469, 1), (740, 1), (1965, 1), (2063, 1), (2346, 1), (2474, 1), (2501, 1), (4172, 1)]


['grand', 'farewell', 

[(92, 1), (93, 1), (656, 1), (832, 1), (1662, 1), (2002, 1), (2302, 1), (5577, 1), (5578, 1), (5579, 1), (5580, 1), (5581, 1), (5582, 1), (5583, 2), (5584, 1)]


['festival', 'ready', 'hook', 'trap', 'inspire', 'production', 'lykke', 'li', 'deliver', 'record', 'unravel', 'romance', 'fraught', 'sexuality', 'final', 'moment', 'diminishing', 'return']
[(19, 1), (47, 1), (115, 1), (252, 1), (478, 1), (495, 1), (521, 1), (788, 1), (1622, 1), (1623, 1), (2844, 1), (4431, 1), (4691, 1), (5585, 1), (5586, 1), (5587, 1), (5588, 1), (5589, 1)]


['eighth', 'followill', 'brother', 'desperately', 'cling', 'stop', 'work', 'try', 'write', 'soar', 'capable', 'one', 'wallow']
[(207, 1), (794, 1), (811, 1), (1122, 1), (2751, 1), (2887, 1), (3576, 1), (3669, 1), (5320, 1), (5321, 1), (5322, 1), (5323, 1), (5324, 1)]


['new', 'n.e.r.d', '.', 'full', 'guest', 'rihanna', 'kendrick', 'gucci', 'm.i.a', 'wale', 'sheeran', 'help', 'elevate', 'occasionally', 'ineffectual', 'attempt', 'protest']
[(5, 1), (15, 1

IndexError: index 5931 is out of bounds for axis 1 with size 5931

In [48]:
num_topics = 10

In [49]:
T = np.zeros((num_topics,len(pf3.artists_list)))
T.shape

(10, 1201)

In [66]:
def vectorize_topic_list(input_topic_list):
    t_vec = np.zeros((num_topics))
    t_vec[np.array(tl).T.astype(int)[0]] = np.array(tl).T[1]
    return t_vec

In [67]:
tl = pf3.lda_model.get_document_topics(test_bow)

In [61]:
t_vec

array([0.        , 0.        , 0.        , 0.90744591, 0.01121614,
       0.        , 0.01117831, 0.        , 0.01020682, 0.01264295])

In [68]:
pprint(vectorize_topic_list(pf3.lda_model.get_document_topics(test_bow)))

array([0.        , 0.        , 0.        , 0.90744591, 0.01121614,
       0.        , 0.01117831, 0.        , 0.01020682, 0.01264295])


In [70]:
id2word = corpora.Dictionary(pf3.tokenized_reviews)

In [76]:
pprint(np.sum(T,axis=0))

array([   0.        ,    0.        ,    0.        , 1089.84253502,
         13.47058121,    0.        ,   13.42514475,    0.        ,
         12.25838576,   15.18417714])


In [164]:
artist2tvec = {}
threshold_prob = 0.7
num_topics=10

def vectorize_topic_list(input_topic_list):
    t_vec = np.zeros((num_topics))
    t_vec[np.array(input_topic_list).T.astype(int)[0]] = np.array(input_topic_list).T[1]
    return np.where(t_vec>threshold_prob, t_vec, 0)

def turn_input_str_into_vec(input_str):
    input_bow = id2word.doc2bow(pf3.narrow_to_vocabulary(pf3.super_tokenize(input_str)))
    input_topics = pf3.lda_model.get_document_topics(input_bow, minimum_probability=threshold_prob)
    print(input_topics)
    return vectorize_topic_list(input_topics)

def create_topic_matrix():
    T_ = np.zeros((len(pf3.artists_list),num_topics))

    for i,rev_tok in enumerate(pf3.tokenized_reviews):
        rev_bow = id2word.doc2bow(rev_tok)
        artist2tvec[pf3.artists_list[i]] = rev_bow
        T_[i] = vectorize_topic_list(rev_bow)
    return T_

def get_artist_probs(t_mat, input_vec):
    return np.dot(T, test_input_vec.T).T

In [113]:
topic_matrix = create_topic_matrix()
test_input = turn_input_str_into_vec("i like songs that are really cool and funky")

print(topic_matrix.shape)
print(test_input.shape)

(1201, 10)
(10,)


In [114]:
test_result = get_artist_probs(topic_matrix, test_input)

In [115]:
pprint(test_result)

array([0.82345808, 0.82345808, 0.82345808, ..., 0.82345808, 0.82345808,
       0.82345808])


In [119]:
pf3.lda_model.get_topics().shape

(10, 5931)

In [120]:
len(pf3.vocabulary)

2615

In [121]:
pf3.export_lda_model("draft_lda_model.pk")

In [144]:
topic_matrix = create_topic_matrix()
print(topic_matrix.shape)

(1201, 10)


## new

In [122]:
lda_model = pickle.load(open("draft_lda_model.pk", "rb"))

In [125]:
lda_model.get_topic_terms(2)

[(281, 0.00677329),
 (5, 0.006293109),
 (60, 0.0055449293),
 (115, 0.005353625),
 (95, 0.005332123),
 (30, 0.0051963613),
 (283, 0.0048516234),
 (860, 0.0038907505),
 (2048, 0.0038861434),
 (59, 0.0037295318)]

In [127]:
tf_idf = pd.read_csv("https://raw.githubusercontent.com/chynu/cs4300sp2021-ag2496-cc972-mb2359-jjz67-jxl8/master/data/processed/tfidf_mat_compressed.csv")
artist_names = tf_idf.values[:,0]

In [137]:
cleaned_artist_names = np.array([pf3.clean(a, cap_code=1) for a in artist_names])

In [138]:
len(cleaned_artist_names)

4013

In [139]:
len(pf3.artists_list)

1201

In [140]:
print(len(set(cleaned_artist_names).intersection(set(pf3.artists_list))))

1194


## create topic matrix that is compatible with searchcontroller tfidf

In [150]:
a_to_i = {a:i for i,a in enumerate(cleaned_artist_names)}

In [152]:
def fitted_matrix(input_topic_matrix, artist_to_idx):
    f_mat = np.zeros((len(artist_to_idx),input_topic_matrix.shape[1]))
    for i,a_row in enumerate(input_topic_matrix):
        a_name = pf3.artists_list[i]
        if a_name in artist_to_idx:
            f_mat[artist_to_idx[a_name]] = input_topic_matrix[i]
    return f_mat

In [153]:
final_mat = fitted_matrix(topic_matrix, a_to_i)

In [154]:
final_mat.shape

(4013, 10)

In [155]:
tf_idf.shape

(4013, 41)

In [156]:
pickle.dump(final_mat, open("../../app/static/var/draft_topic_matrix.pk", "xb"))

In [158]:
pf3.export_count_vectorizer("../../app/static/var/pf_cvec.pk")
pf3.export_tfidf_vectorizer("../../app/static/var/pf_tfidfvec.pk")

In [159]:
pickle.dump(pf3.tokenized_reviews, open("../../app/static/var/draft_tokenized_reviews.pk", "xb"))

In [160]:
pickle.dump(pf3.stop_words, open("../../app/static/var/stop_words.pk", "xb"))

In [165]:
turn_input_str_into_vec("asdf")

[]


IndexError: index 1 is out of bounds for axis 0 with size 0